apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
spec:
  selector:
    matchLabels:
      run: reverseproxy
  replicas: 2
  template:
    metadata:
      labels:
        run: reverseproxy
    spec:
      containers:
      - name: reverseproxy
        image: docker.io/igwubor/reverseproxy:v1
        ports:
        - containerPort: 80
        livenessProbe:
          exec:
            command:
              - cat
              - /tmp/healthy
          periodSeconds: 360
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m