apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  AWS_ACCESS_KEY_ID: AKIAW4AXEZWWB7U7WH7A
  AWS_SECRET_ACCESS_KEY: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVc0QVhFWldXQjdVN1dIN0EK
type: Opaque